-- Seed line mappings into ecbconfigs table
INSERT INTO ecbconfigs (section, variable, value, ordering, created_at, updated_at) VALUES
('line_mapping', 'REF A', '1', '001', NOW(), NOW()),
('line_mapping', 'REF B', '2', '002', NOW(), NOW()),
('line_mapping', 'REF C', '3', '003', NOW(), NOW()),
('line_mapping', 'REF D', '4', '004', NOW(), NOW()),
('line_mapping', 'REF E', '5', '005', NOW(), NOW()),
('line_mapping', 'REF F', '6', '006', NOW(), NOW()),
('line_mapping', 'REF G', '7', '007', NOW(), NOW()),
('line_mapping', 'REF H', '8', '008', NOW(), NOW()),
('line_mapping', 'REF I', '9', '009', NOW(), NOW()),
('line_mapping', 'REF J', '10', '010', NOW(), NOW()),
('line_mapping', 'PWM', '11', '011', NOW(), NOW()),
('line_mapping', 'PWM 1', '11', '012', NOW(), NOW()),
('line_mapping', 'PAW', '12', '013', NOW(), NOW()),
('line_mapping', 'DISPENSER', '14', '014', NOW(), NOW()),
('line_mapping', 'DISPENSER 1', '14', '015', NOW(), NOW()),
('line_mapping', 'PAC', '15', '016', NOW(), NOW()),
('line_mapping', 'AC_INDOOR', '15', '017', NOW(), NOW()),
('line_mapping', 'AC_INDOOR 1', '15', '018', NOW(), NOW()),
('line_mapping', 'SAP', '16', '019', NOW(), NOW()),
('line_mapping', 'PWM 2', '17', '020', NOW(), NOW()),
('line_mapping', 'AC_INDOOR 2', '18', '021', NOW(), NOW()),
('line_mapping', 'AC_OUTDOOR 1', '19', '022', NOW(), NOW()),
('line_mapping', 'AC_OUTDOOR 2', '20', '023', NOW(), NOW()),
('line_mapping', 'CHEST_FREEZER', '21', '024', NOW(), NOW());
